### PR TITLE
fix(openapi): handle nullable `$ref` in a valid way for OpenAPI 3.0 using `allOf`

### LINKED ISSUE #349: `convertToOpenApi3Point0` produces invalid OpenAPI 3.0 for nullable `$ref` schemas
When converting nullable `$ref` schemas for OpenAPI 3.0, `convertToOpenApi3Point0` currently collapses the schema to `{ $ref: '#/components/schemas/Author', nullable: true }`. OpenAPI 3.0 does not allow `$ref` to have sibling properties, so this output is invalid and breaks some generators. The conversion should instead wrap the ref in `allOf` and put `nullable: true` on the wrapper schema.

This is documented under [“$ref and Sibling Elements” in the Swagger docs](https://swagger.io/docs/specification/v3_0/using-ref#considerations):  

### Reproduction (minimal)

```ts
import { JSONSchema } from 'zod/v4/core';
import { convertToOpenApi3Point0 } from './utils';

const schema: JSONSchema.BaseSchema = {
  type: 'object',
  properties: {
    // Author.nullable()
    author: {
      anyOf: [
        { $ref: '#/components/schemas/Author' },
        { type: 'null' },
      ],
    },
  },
};

const converted = convertToOpenApi3Point0(schema);
console.log(JSON.stringify(converted, null, 2));
```

### Actual output (simplified)

```json
{
  "type": "object",
  "properties": {
    "author": {
      "$ref": "#/components/schemas/Author",
      "nullable": true
    }
  }
}
```

This is invalid in OpenAPI 3.0 because `$ref` has a sibling property (`nullable`).

### Expected output

```json
{
  "type": "object",
  "properties": {
    "author": {
      "allOf": [
        { "$ref": "#/components/schemas/Author" }
      ],
      "nullable": true
    }
  }
}
```

This keeps the schema OpenAPI 3.0‑compliant while still signaling nullability, allowing clients to safely generate types like `Author | null`.

### PR DESCRIPTION
**Pull request by timonrieger**
fixes #349

implemented as explained in the issue

### CODE REVIEW

File: packages/nestjs-zod/src/utils.ts [hunk 1]
```diff
@@ -53,8 +53,13 @@ export function convertToOpenApi3Point0(schema: JSONSchema.BaseSchema) {
       const { anyOf, ...rest } = s;
 
       if (anyOf.length === 1) {
+        const sole = anyOf[0];
+        // OpenAPI 3.0: $ref cannot have sibling properties (e.g. nullable); keep anyOf form
+        if (sole.$ref && Object.keys(sole).length === 1) {
+          return { anyOf: [sole, { type: 'null' }], ...rest };
```
Comment (BenLorantfy) [inline packages/nestjs-zod/src/utils.ts]: But `type: 'null'` is not supported in openapi 3.0?  So I don't think this fully solves the problem.

What about this:

```suggestion
          return { 
            ...rest,
            nullable: true,
            allOf: [sole]
          };
```


We should also fix the bug in the case of `anyOf.length > 1`

**Review by BenLorantfy — CHANGES_REQUESTED** [review]

**Comment by timonrieger** [comment]
fixed all comments, `allOf` works on my generators
